baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Samuel May'
theme = 'anatole'
[params]
title = "Sam's Website"
author = 'Samuel May'
description = 'Full stack web developer'
profilePicture = 'images/profilePicture.jpg'

